version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  orchestrator:
    build: ./orchestrator
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./videos:/data/videos
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URL=mongodb://mongodb:27017
    command: python orchestrator.py
    
  worker_480p:
    build: ./worker_480p
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./videos:/data/videos
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URL=mongodb://mongodb:27017
    command: celery -A celery_app worker -Q transcode_480p --loglevel=info
    restart: unless-stopped
    
  worker_720p:
    build: ./worker_720p
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./videos:/data/videos
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URL=mongodb://mongodb:27017
    command: celery -A celery_app worker -Q transcode_720p --loglevel=info --concurrency=1
    restart: unless-stopped

  worker_1080p:
    build: ./worker_1080p
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./videos:/data/videos
    environment:
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URL=mongodb://mongodb:27017
    command: celery -A celery_app worker -Q transcode_1080p --loglevel=info --concurrency=1
    restart: unless-stopped

volumes:
  mongo_data: